spring.application.name=hive-ingest-service

# Perfil activo por defecto (forzamos local para que el dev cree su application-local.properties)
spring.profiles.active=${APP_PROFILE:local}

# Configuracion global de Springdoc / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method